### ISSUE TITLE
Реализовать подключение к серверу

### ISSUE THREAD

**Issue by born66613** [ledmitr/TheBestGameEver#20]
Необходимо подключится реализовать процесс подключения клиента к серверу и обеспечить их взаимодействие по алгоритму, описанному в разделе Wiki - сетевое взаимодействие (первые три этапа)

**Comment by ledmitr** [comment]
Со стороны сервера взаимодействие готово

**Comment by born66613** [comment]
сделано, все работает

**Comment by born66613** [comment]
закинули
