### ISSUE TITLE
Task #6 Соглашение по API взаимодействию между клиентом и сервером

### ISSUE THREAD

**Issue by skyBodrik** [ledmitr/TheBestGameEver#6]
Ребята, нам нужно прийти к консенсусу по поводу стандартизации api запросов на сервер со стороны клиента, ну и также ответов сервера клиенту. Тут принимаем решения вместе. По закрытию данной задачи, должен получится единый документ, который будет содержать список всех api вызовов, формат запросов и ответов, а также примеры их реализации.

**Comment by ledmitr** [comment]
Готов черновой вариант описания:
https://github.com/ledmitr/TheBestGameEver/wiki/%D0%A1%D0%B5%D1%82%D0%B5%D0%B2%D0%BE%D0%B5-%D0%B2%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5
